[package]
name = "fat32"
version = "0.1.0"
authors = ["Sergio Benitez <sb@sergio.bz>"]

[features]
custom_std = ["std"]

[dependencies]
std = { path = "../../os/std", optional = true }
byteorder = { version = "1", default-features = false }

[dev-dependencies]
rand = "0.4"
